// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "medify-webapp-medify",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d287rfzw5agg4p.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:7b70a6a2-b31f-4399-a8aa-6fbb30aea51c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_EN3uRlqQB",
    "aws_user_pools_web_client_id": "71e53bgsr68pvi54sobk65r16p",
    "oauth": {}
};


export default awsmobile;
